// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXmyFb2qDYymE7hM7Qkdo94NR5tqDQvVg',
    appId: '1:659268634419:web:0a5fc939a6757ca76d6046',
    messagingSenderId: '659268634419',
    projectId: 'cureconnect-4763e',
    authDomain: 'cureconnect-4763e.firebaseapp.com',
    storageBucket: 'cureconnect-4763e.firebasestorage.app',
    measurementId: 'G-QX2MD42C8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCfMStS1J7rfkU9tbsITUVLVFLQCtfgSg',
    appId: '1:659268634419:android:0cd4b23690f9ccb16d6046',
    messagingSenderId: '659268634419',
    projectId: 'cureconnect-4763e',
    storageBucket: 'cureconnect-4763e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuW5yBMNmTHnJgiLqzEuriX0_YYCFAO5E',
    appId: '1:659268634419:ios:db5d55cf3602bf3f6d6046',
    messagingSenderId: '659268634419',
    projectId: 'cureconnect-4763e',
    storageBucket: 'cureconnect-4763e.firebasestorage.app',
    iosBundleId: 'com.example.cureconnectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXmyFb2qDYymE7hM7Qkdo94NR5tqDQvVg',
    appId: '1:659268634419:web:8f7fe9965e1e2df66d6046',
    messagingSenderId: '659268634419',
    projectId: 'cureconnect-4763e',
    authDomain: 'cureconnect-4763e.firebaseapp.com',
    storageBucket: 'cureconnect-4763e.firebasestorage.app',
    measurementId: 'G-JX4Z7ZCKXE',
  );
}
